---
- name: Tomcat 9 Installation
  become: yes
  hosts: all
  vars:
        - username: tomcat
        - default_shell: /bin/false
        - home_dir: /opt/tomcat
        - tomcat_version: 9.0.71
        - tomcat_latest: /opt/tomcat/latest
        - tomcat_bin_directory: /opt/tomcat/latest/bin
        - tomcat_service_location: /etc/systemd/system/
  tasks:     
    - name: Update the Packages Repos & Cache
      yum:
        update_cache: yes
      when: ansible_facts['os_family'] == "RedHat"  
    - name: Install openjdk 11
      package:
        name: "{{ java_package }}"
        state: present
    
    - name: Create a tomcat user
      ansible.builtin.user:
        create_home: yes
        home: "{{ home_dir }}"
        shell: "{{ default_shell }}"
        name: "{{ username }}"
      when: ansible_facts['os_family'] == "RedHat"
    
    - name: Downlaod tomcat 9
      ansible.builtin.get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
      when: ansible_facts['os_family'] == "RedHat"  
    
    - name: Extract tomcat 9
      ansible.builtin.unarchive:
        creates: "{{ home_dir }}/apache-tomcat-{{ tomcat_version }}"
        src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ home_dir }}"
        remote_src: yes
      when: ansible_facts['os_family'] == "RedHat"
    
    - name: Create a Symbolic link
      ansible.builtin.file:
        src: "{{ home_dir }}/apache-tomcat-{{ tomcat_version }}"
        dest: "{{ tomcat_latest }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        state: link
      when: ansible_facts['os_family'] == "RedHat"
       
    - name: Change the ownership to tomcat user
      ansible.builtin.file:
        path: "{{ home_dir }}"
        state: directory
        recurse: yes
        owner: "{{ username }}"
        group: "{{ username }}"
      when: ansible_facts['os_family'] == "RedHat"
    
    - name: find all the .sh files in the tomcat bin directory
      ansible.builtin.find:
        paths: "{{ tomcat_bin_directory }}"
        patterns: "*.sh"
      when: ansible_facts['os_family'] == "RedHat"
      register: sh_files_tomcat_bin
    - name: print the files from the previous
      debug:
        var: sh_files_tomcat_bin
      when: ansible_facts['os_family'] == "RedHat"
    
    - name: Make shell scripts executable
      ansible.builtin.file:
        path: "{{ item.path }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0755'
      loop: "{{ sh_files_tomcat_bin.files }}"
      when: ansible_facts['os_family'] == "RedHat"
    
    - name: copy the tomcat service file
      ansible.builtin.copy:
        src: tomcat.service
        dest: "{{ tomcat_service_location }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        remote_src: yes
        mode: 0755
      when: ansible_facts['os_family'] == "RedHat"
    
    - name: reload the daemon, enable and start the tomcat service
      ansible.builtin.systemd:
        name: tomcat.service
        daemon_reload: yes
        enabled: yes
        state: started
      when: ansible_facts['os_family'] == "RedHat"


