---
- name: LAMP in any Linux
  become: yes
  hosts: webserver
  tasks:

    - name: update library
      apt:
        update_cache: yes

    - name: Install Apache2
      package:
        name: "{{ apache_package }}"
        state: present

    - name: Ensure Apache2 is started
      ansible.builtin.service:
        name: "{{ apache_package }}"
        state: started

    - name: Install php
      package:
        name: "{{ php_packages }}"
        state: present

    - name: Test php on Apache WebServer
      ansible.builtin.copy:
        src: "info.php"
        dest: "{{ php_home }}"
      notify:
        Ensure apache is started & running

  handlers:
    - name: Ensure apache is started & running
      ansible.builtin.systemd:
        name: "{{ apache_package }}"
        daemon_reload: yes
        enabled: yes
        state: restarted
