---
- name: Java Installations...
  become: yes
  hosts: all
  tasks:
    - name: Install Java11 on Ubuntu
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update cache: yes
        state: present
        when: ansible_facts['os_family'] == "Debian"
    - name: Install Java11 on RedHat
      ansible.builtin.yum:
        name: java-11-openjdk
        update cache: yes
        state: present
        when: ansible_facts['os_family'] == "RedHat"