---
- name: Install LAMP on RHEL9.1
  become: yes
  hosts: all
  vars:
    - home_dir: /var/www/html/info.php

  tasks:
    - name: Install Apache
      ansible.builtin.apt:
        pkg:
        - httpd
        state: present
        update_cache: yes

    - name: Ensure Apache is running
      ansible.builtin.systemd:
        name: 'httpd'
        state: 'started'
      notify:
        - reload the daemon, enable and start httpd

    - name: Install php
      ansible.builtin.apt:
        name: php
        state: present
        update_cache: yes
      notify:
        - reload the daemon, enable and start httpd

    - name: Test php on Apache Web Server
      ansible.builtin.copy:
        src: 'info.php'
        dest: "{{ home_dir }}"
      notify:
        - reload the daemon, enable and start httpd

    handlers:    
    - name: reload the daemon, enable and start httpd
      ansible.builtin.systemd:
        name: "httpd"
        daemon_reload: yes
        enabled: yes
        state: restarted