---
- name: Install LAMP stack on Ubuntu
  become: yes
  hosts: all
  vars:
    - home_dir: /var/www/html/info.php
    
  tasks:
    - name: Update the Packages Repos & Cache
      apt:
        update_cache: yes
        force_apt_get: yes
      when: ansible_facts['os_family'] == "Debian"
    
    - name: Install Apache
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes
    
    - name: Install stress
      ansible.builtin.apt:
        name: stress
        state: present
        update_cache: yes
    
    - name: Install php
      ansible.builtin.apt:
        name: php
        state: latest
        update_cache: yes

    - name: Test php on Apache Web Server
      template:
        src: "info.php.j2"
        dest: "{{ home_dir }}"  
      notify:
        - Reload the daemon, enable and start the service
    
    - name: Ensure Apache is running
      ansible.builtin.systemd:
        name: 'apache2'
        state: 'started'
  
  handlers:      
    - name: Reload the daemon, enable and start the service
      ansible.builtin.systemd:
        name: apache2
        daemon_reload: yes
        enabled: yes
        state: restarted