---
- name: Install Java
  become: yes
  hosts: Appserver
  tasks:
    - name: Update libraries
        apt:
          update_cache: yes
    - name: Install openjdk 11
      package:
        name: "{{ java_package }}"
        state: present
    - name: Create a tomcat user
        ansible.builtin.user:
          create_home: yes
          home: /opt/tomcat
          shell: /bin/false
          name: tomcat
    