#!/bin/bash
sudo -i
apt update
apt install apache2 stress -y
apt install php libapache2-mod-php php-mysql -y
echo '<?php phpinfo(); ?>' > info.php
cp info.php /var/www/html
systemctl restart apache2

#sudo apt-get purge apache2 php -y
#sudo apt-get autoremove -y

#!/bin/bash
sudo -i
dnf install httpd -y
systemctl start httpd
sudo systemctl enable httpd
#firewall-cmd --zone-public --permanent --add-service=http
#firewall-cmd --reload
dnf install php -y
systemctl restart httpd
echo '<?php phpinfo(); ?>' > info.php
cp info.php /var/www/html

#sudo dnf purge ahttpd php -y