---
- name: Install Nodejs
  become: yes
  hosts: all
  tasks:
    - name: install NodeJS on RedHat
      ansible.builtin.dnf:
        name: nodejs
        update_cache: yes
        state: present
      when: ansible_facts['os_family'] == "RedHat"
    - name: install NodeJS on Ubuntu
      ansible.builtin.apt:
        name: nodejs
        update_cache: yes
        state: present
      when: ansible_facts['os_family'] == "Debian"