---
- name: Install Tomcat 10
  become: yes
  hosts: all
  tasks:
    - name: update apt repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
      when: ansible_facts['os_family'] == "Debian"
    - name: install openjdk 11
      package:
        name: "{{ java_package }}"
        state: present 
    - name: creating a tomcat user
      ansible.builtin.user:
        create_home: yes
        home: /opt/tomcat
        name: tomcat
        shell: /bin/false
        state: present
      when: ansible_facts['os_family'] == "Debian"  
#    - name: wget
#      ansible.builtin.get_url:  
#       url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
#        dest: /opt/tomcat
