---
- name: Install Tomcat on Ubuntu 
  hosts: appserver
  become: yes
  vars:
    - username: tomcat
    - java_home: /usr/lib/jvm/java-11-openjdk-amd64
    - home_dir: /opt/tomcat
    - default_shell: /bin/false
    - tomcat_version: 9.0.71
    - tomcat_latest: /opt/tomcat/latest
    - tomcat_bin_directory: /opt/tomcat/latest/bin
    - tomcat_service_location: /etc/systemd/system/tomcat.service
    - tomcat_admin_user: devops
    - tomcat_admin_password: devops
    - tomcat_users_relative: conf/tomcat-users.xml
    - tomcat_manager_allow_ipregex: ".*"
    - tomcat_allow_context_locations:
        - /opt/tomcat/latest/webapps/manager/META-INF/context.xml
        - /opt/tomcat/latest/webapps/host-manager/META-INF/context.xml
    - deploy_url: https://sg.mirror.servanamanaged.com/jenkins/war-stable/2.375.3/jenkins.war
    - deploy_file_name: jenkins.war

  tasks:
    - name: Update library
      apt:
        update_cache: yes
        force_apt_get: yes
      when: ansible_facts['os_family'] == "Debian"
    - name: Install Java
      package:
        name: "{{ java_package }}"
        state: present 
    - name: Create Tomcat user
      ansible.builtin.user:
        name: "{{ username }}"
        create_home: yes
        home: "{{ home_dir }}"
        shell: "{{ default_shell }}"
        state: present 
    - name: Download Tomcat 9
      ansible.builtin.get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"  
    - name: Extract the tar file
      ansible.builtin.unarchive:
        creates: "{{ home_dir }}/apache-tomcat-{{ tomcat_version }}"
        src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ home_dir }}"
        remote_src: yes
    - name: Create a symbolic link
      ansible.builtin.file:
        src:  "{{ home_dir }}/apache-tomcat-{{ tomcat_version }}"
        dest: "{{ tomcat_latest }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        state: link
    - name: Change the ownership for tomcat user
      ansible.builtin.file:
        path: "{{ home_dir }}" 
        owner: "{{ username }}"
        group: "{{ username }}"
        state: directory
        recurse: yes  
    - name: find all .sh files in the tomcat bin directory
      ansible.builtin.find:
        paths: "{{ tomcat_bin_directory }}"
        patterns: "*.sh"
      register: sh_files_tomcat_bin
    - name: Print o/p of previous module
      debug: 
        var: sh_files_tomcat_bin
    - name: Make .sh files Executables
      ansible.builtin.file:
        path: "{{ item.path }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0755'
      loop: "{{ sh_files_tomcat_bin.files }}"
    - name: Copy the tomcat service file
      ansible.builtin.template:
        src: 'tomcat.service.j2' 
        dest: "{{ tomcat_service_location }}"
        owner: "{{ username }}"
        group: "{{ username }}"
      notify:
        - Reload the daemon, enable and start the tomcat service
    - name: Force all notified handlers to run at this point, not waiting for normal sync points    
      meta: flush_handlers
    - name: ensure tomcat service is running
      ansible.builtin.systemd:
        name: 'tomcat.service'
        state: 'started'
    - name: create the tomcat users file
      ansible.builtin.template:
        src: 'tomcat-users.xml.j2'
        dest: "{{ tomcat_latest }}/{{ tomcat_users_relative }}"
        owner: "{{ username }}"
        group: "{{ username }}"
      notify:
        - Reload the daemon, enable and start the tomcat service
    - name: Allow manager and hostmanager from specified ip range
      ansible.builtin.template:
        src: 'manager-context.xml.j2'
        dest: "{{ item }}"
        owner: "{{ username }}"
        group: "{{ username }}"
      loop: "{{ tomcat_allow_context_locations }}"
      notify:
        - Reload the daemon, enable and start the tomcat service
    - name: Deploy any war file
      ansible.builtin.get_url:
        url: "{{ deploy_url }}"
        dest: "{{ tomcat_latest }}/webapps/{{ deploy_file_name }}"
      notify:
        - Reload the daemon, enable and start the tomcat service
  handlers:      
    - name: Reload the daemon, enable and start the tomcat service 
      ansible.builtin.systemd:
        name: 'tomcat.service'
        daemon_reload: yes
        enabled: yes
        state: restarted 
