---
- name: Install L.A.M.P stack on RedHat/CentOS
  become: yes
  hosts: all
  vars:
    - username: jimmy
    - password: jimmy
    - home_dir: /var/www/html/
 
  tasks:
    - name: Create a user                                    # sudo adduser devops
      ansible.builtin.user:
        create_home: yes
        name: "{{ username }}"
        password: "{{ username }}"
        home: "{{ home_dir }}"
        shell: "{{ default_shell }}"
        state: present
    - name: Install Apache Web Server
      ansible.builtin.dnf:
        name: httpd
        state: latest
    - name: Install php
      ansible.builtin.dnf:
        name: php
        state: latest
    - name: Ensure Apache is running
      ansible.builtin.systemd:
        name: httpd
        state: started
    - name: Reload the daemon, enable and start the service
      ansible.builtin.systemd:
        name: httpd
        daemon_reload: yes
        enabled: yes
<<<<<<< HEAD
        state: restarted    
=======
        state: restarted
    - name: Install php
      ansible.builtin.dnf:
        name: php
        state: latest
>>>>>>> 2add2465e505b59932cb0cc0089c3c601d202150
    - name: Change ownership
      ansible.builtin.file:
        path: "{{ home_dir }}"
        state: directory
        recurse: yes
        owner: "{{ username }}"
        group: "{{ username }}"
    - name: Test PHP on Apache Web Server
      ansible.builtin.copy:
        src: 'php.service'
        dest: "/var/www/html/info.php"
        owner: "{{ username }}"
        group: "{{ username }}"

          
