---
- name: Install L.A.M.P stack on RedHat/CentOS
  become: yes
  hosts: all
  vars:
    - username: jimmy
    - home_dir: /var/www/html/
 
  tasks:
    - name: Install Apache Web Server
      ansible.builtin.dnf:
        name: httpd
        state: latest
      notify:
        - Reload the daemon, enable and start Apache
    - name: Ensure Apache is running
      ansible.builtin.systemd:
        name: httpd
        state: started
  handlers:      
    - name: Reload the daemon, enable and start the service
      ansible.builtin.systemd:
        name: httpd
        daemon_reload: yes
        enabled: yes
        state: restarted
    - name: Install php
      ansible.builtin.dnf:
        name: php
        state: latest
    - name: Change ownership
      ansible.builtin.file:
        path: "{{ home_dir }}"
        state: directory
        creates: "/var/www/html/info.php"
        recurse: yes
        owner: "{{ username }}"
        group: "{{ username }}"
    - name: Test PHP on Apache Web Server
      ansible.builtin.copy:
        src: 'php.service'
        dest: "/var/www/html/info.php"
        owner: "{{ username }}"
        group: "{{ username }}"

          
