---
- name: Install nopCommerce on ubuntu
  become: yes
  hosts: all
  vars:
    -

  tasks:
    - name: update library
      apt:
        update_cache: yes
        force_apt_get: yes
      when: ansible_facts['os_family'] == "Debian"
    - name: Register Microsoft key and feed
      ansible.builtin.get_url:
        url: "https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb"
        dest: "/tmp/packages-microsoft-prod.deb"
    - name: Install MS product repository
      apt:
        name: packages-microsoft-prod.deb
        selection: install
    - name: Make sure HTTPS is supported by apt
      apt:
        name: apt-transport-https
        state: present
    - name: Install .NET Core SDK
      apt:
        name: dotnet-sdk-6.0
        state: present
        update_cache: yes
    - name: Install MySql
      community.mysql.mysql_db:
        name: mysql
        

    

