---
- name: Install L.A.M.P stack on Ubuntu & RedHat
  become: yes
  hosts: all
  vars:
    - home_dir: /var/www/html/

  tasks:
    - name: Update apt repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
    - name: Install Apache2
      ansible.builtin.apt:
        name: apache2
        state: present
    - name: Install php
      ansible.builtin.apt:
        name: php
        update_cache: yes
        state: latest
    - name: Test php on Apache Web Server
      ansible.builtin.copy:
        src: 'php.service'
        dest: "{{ home_dir }}/info.php"    
      notify:
        - Reload the daemon, enable and start the service
    - name: Ensure Apache is running
      ansible.builtin.systemd:
        name: 'apache2'
        state: 'started'
  handlers:      
    - name: Reload the daemon, enable and start the service
      ansible.builtin.systemd:
        name: apache2
        daemon_reload: yes
        enabled: yes
        state: restarted 
        

