---
- name: Install NodeJS
  become: yes
  hosts: all
  tasks:
    - name: Update the Package Repos & Cache
      apt:
        force_apt_get: yes
      when: ansible_facts['os_family'] == "Debian"
    - name: NodeJS Installations
      package:
        name: "{{ NodeJS_package }}"
        state: present
